server:
  port: 2002

eureka:
  instance:
    hostname: eureka2002 #eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己。
    fetch-registry: false # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://localhost:2003/eureka/ # 集群指向其他地址
      # defaultZone: http://localhost:2003/eureka/ # 单机指向自己
      defaultZone: http://eureka2003.com:2003/eureka/ # 写成这样可以直接通过可视化页面跳转到2003

