server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址，注册到Nacos
# 做监控需要把这个全部暴露出来
management:
  endpoints:
    web:
      exposure:
        include: '*'
