server:
  port: 3002 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址，注册到Nacos

    gateway:
      routes: # 网关路由配置
        - id: cloud-user #路由的ID，没有固定规则但要求唯一，建议配合微服务名
          # uri: http://localhost:1001 # 路由的目标地址（http就是固定地址）
          uri: lb://cloud-user # 路由的目标地址（lb就是负载均衡，后面跟服务名称）
          predicates: # 判断请求是否符合路由规则的条件（路由断言）
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        # 上面表示 访问网关http://localhost:3001/user/** 会访问到http://cloud-user/user/**

      default-filters: #默认过滤器，会对所有的路由请求都生效
        - AddRequestHeader=origin,gateway # 添加名为origin的请求头，值为gateway
