server:
  port: 1001

spring:
  application:
    name: cloud-user # 微服务唯一标识
  datasource:
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 #采样率值介于 0 到 1 之间，1 则表示全部采集

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进Eurekaserver服务，默认为true。
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:2001/eureka # eureka单机服务的地址
  instance:
    instance-id: user1001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)，开发时设置小些，保证服务关闭后注册中心能即使剔除服务
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wen.springcloud.entities # 所有Entity别名类所在包

