server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:

      routes:
        - id: payment_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE # lb 为负载均衡
          predicates:
            - Path=/**   #断言,路径相匹配的进行路由 表示 如果要访问http://localhost:8001/get/payment/** 需要访问http://localhost:9527/get/payment/**
            - After=2023-02-10T10:10:10.102+08:00[Asia/Shanghai] # 匹配该断言时间之后的 uri请求
            - Cookie=username,wen    #需要带cookie并且Cookie是username=wen才能访问
            #- Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.wen.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由
        - id: payment_routh2
          uri: http://localhost:8002
          predicates:
            - Path=/**   #断言,路径相匹配的进行路由
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
