server:
  port: 1003

spring:
  application:
    name: cloud-user1003
  datasource:
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进Eurekaserver服务，默认为true。
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # defaultZone: http://localhost:2001/eureka # eureka单机服务的地址
      defaultZone: http://eureka2002.com:2002/eureka/, http://eureka2003.com:2003/eureka/ # eureka集群服务的地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wen.springcloud.entities # 所有Entity别名类所在包

