server:
  port: 1004

spring:
  application:
    name: cloud-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wen.springcloud.entities # 所有Entity别名类所在包

